name: Test & Lint

on:
  pull_request:
  push:

jobs:
    test-lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install poetry
          run: pipx install poetry
        - uses: actions/setup-python@v4
          with:
            python-version: 3.11
            cache: 'poetry'
        - name: Poetry Version
          run: |
            poetry --version
        - name: Poetry Install Dependencies
          run: |
            poetry install --with dev --no-interaction
        - name: Run pylint
          run: poetry run pylint ./*.py
        - name: Run pytest
          run: poetry run pytest