name: Help test

on:
  pull_request:
  push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install poetry
          run: pipx install poetry
        - uses: actions/setup-python@v4
          with:
            python-version: 3.11
            cache: 'poetry'
        - name: Poetry Version
          run: |
            poetry --version
        - name: Poetry Install Dependencies
          run: |
            poetry install --no-interaction
        - name: Run --help
          run: SECRET_KEY="foobar" poetry run python main.py --help